Use "std::print" instead of "printf".
C++ formatting functions should be used instead of C printf-like functions cpp:S6494

But std::print() is not available:

[build] /home/alexander/Technik/Development/codecrafters-http-server-cpp/src/server.cpp: In function ‘void send_response(int, http_response_struct, int, const char*, const char*)’:
[build] /home/alexander/Technik/Development/codecrafters-http-server-cpp/src/server.cpp:65:14: error: ‘print’ is not a member of ‘std’; did you mean ‘printf’?
[build]    65 |         std::print("send_response()\n");
[build]       |              ^~~~~
[build]       |              printf